version: '3.1'

services:
  
  db:
    image: mysql:5.7 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: typingtest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql 

  
  flyway:
    image: flyway/flyway
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql 
    command: -url=jdbc:mysql://db:3306/typingtest -user=user -password=password migrate


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password


  app:
    build: . 
    restart: always
    ports:
      - '5672:5672' 
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: typingtest
    volumes:
      - .:/app 

volumes:
  db_data:
